git rm app/controllers/graphs_controller.rb
git rm app/controllers/voted_vote_topics_controller.rb
git rm app/helpers/category_helper.rb
git rm app/helpers/graphs_helper.rb
git rm app/helpers/voted_vote_topics_helper.rb
git rm app/models/voted_vote_topic.rb
git rm app/views/account/_vote_list.html.erb
git rm app/views/account/approve_vote.js.erb
git rm app/views/account/index.js.erb
git rm app/views/category/_cat_nav_list.html.erb
git rm app/views/friend_invite_messages/create.html.erb
git rm app/views/graphs/age_graph.html.erb
git rm app/views/graphs/gender_graph.html.erb
git rm app/views/home/_latest_votes.html.erb
git rm app/views/home/_local_votes.html.erb
git rm app/views/home/_most_tracked_votes.html.erb
git rm app/views/home/_top_voters.html.erb
git rm app/views/home/_top_votes.html.erb
git rm app/views/home/_tracked_votes.html.erb
git rm app/views/home/_unan_votes.html.erb
git rm app/views/home/_whos_voting.erb
git rm app/views/layouts/_category_side_bar.html.erb
git rm app/views/layouts/_rpx.html.erb
git rm app/views/layouts/_user_side_bar.html.erb
git rm app/views/layouts/_vote_side_bar.html.erb
git rm app/views/layouts/searches.html.erb
git rm app/views/layouts/users.html.erb
git rm app/views/layouts/vote_topics.html.erb
git rm app/views/notifier/activation_confirmation.erb
git rm app/views/notifier/activation_instructions.erb
git rm app/views/notifier/password_reset_instructions.erb
git rm app/views/shared/_tracking_tooltip.html.erb
git rm app/views/users/index.html.erb
git rm app/views/voted_vote_topics/_voted.html.erb
git rm app/views/voted_vote_topics/index.html.erb
git rm app/views/voted_vote_topics/index.js.erb
git rm lib/periodic_facet_job.rb
git rm lib/periodic_job.rb
git rm lib/periodic_small_job.rb
git rm lib/vote_process_job.rb
git rm public/images/vert_large.png
git rm public/stylesheets/images/ui-anim_basic_16x16.gif
git rm public/stylesheets/images/ui-bg_flat_0_eeeeee_40x100.png
git rm public/stylesheets/images/ui-bg_flat_55_ffffff_40x100.png
git rm public/stylesheets/images/ui-bg_flat_75_ffffff_40x100.png
git rm public/stylesheets/images/ui-bg_glass_65_ffffff_1x400.png
git rm public/stylesheets/images/ui-bg_highlight-soft_100_f6f6f6_1x100.png
git rm public/stylesheets/images/ui-bg_highlight-soft_25_0073ea_1x100 (copy).png
git rm public/stylesheets/images/ui-bg_highlight-soft_25_0073ea_1x100.png
git rm public/stylesheets/images/ui-bg_highlight-soft_25_0073ea_1x100_orig.png
git rm public/stylesheets/images/ui-bg_highlight-soft_50_dddddd_1x100.png
git rm public/stylesheets/images/ui-bg_highlight-softer.png
git rm public/stylesheets/images/ui-icons_0073ea_256x240.png
git rm public/stylesheets/images/ui-icons_454545_256x240.png
git rm public/stylesheets/images/ui-icons_666666_256x240.png
git rm public/stylesheets/images/ui-icons_ff0084_256x240.png
git rm public/stylesheets/jquery-ui-1.8.2.custom.css
git rm public/stylesheets/scaffold.css
git rm test/functional/category_controller_test.rb
git rm test/functional/graphs_controller_test.rb
git rm test/functional/voted_vote_topics_controller_test.rb
git rm test/unit/helpers/category_helper_test.rb
git rm test/unit/helpers/graphs_helper_test.rb
git rm test/unit/helpers/voted_vote_topics_helper_test.rb
git rm vendor/plugins/exception_notification/README
git rm vendor/plugins/exception_notification/exception_notification.gemspec
git rm vendor/plugins/exception_notification/init.rb
git rm vendor/plugins/exception_notification/lib/exception_notification.rb
git rm vendor/plugins/exception_notification/lib/exception_notification/consider_local.rb
git rm vendor/plugins/exception_notification/lib/exception_notification/notifiable.rb
git rm vendor/plugins/exception_notification/lib/exception_notification/notifier.rb
git rm vendor/plugins/exception_notification/lib/exception_notification/notifier_helper.rb
git rm vendor/plugins/exception_notification/lib/exception_notifier.rb
git rm vendor/plugins/exception_notification/lib/exception_notifier/notifier.rb
git rm vendor/plugins/exception_notification/lib/exception_notifier/views/exception_notifier/_backtrace.text.erb
git rm vendor/plugins/exception_notification/lib/exception_notifier/views/exception_notifier/_environment.text.erb
git rm vendor/plugins/exception_notification/lib/exception_notifier/views/exception_notifier/_request.text.erb
git rm vendor/plugins/exception_notification/lib/exception_notifier/views/exception_notifier/_session.text.erb
git rm vendor/plugins/exception_notification/lib/exception_notifier/views/exception_notifier/_title.text.erb
git rm vendor/plugins/exception_notification/lib/exception_notifier/views/exception_notifier/exception_notification.text.erb
git rm vendor/plugins/exception_notification/test/exception_notifier_helper_test.rb
git rm vendor/plugins/exception_notification/test/test_helper.rb
git rm vendor/plugins/exception_notification/views/exception_notifier/_backtrace.rhtml
git rm vendor/plugins/exception_notification/views/exception_notifier/_environment.rhtml
git rm vendor/plugins/exception_notification/views/exception_notifier/_inspect_model.rhtml
git rm vendor/plugins/exception_notification/views/exception_notifier/_request.rhtml
git rm vendor/plugins/exception_notification/views/exception_notifier/_session.rhtml
git rm vendor/plugins/exception_notification/views/exception_notifier/_title.rhtml
git rm vendor/plugins/exception_notification/views/exception_notifier/exception_notification.rhtml
git rm vendor/plugins/open_flash_chart/MIT-LICENSE
git rm vendor/plugins/open_flash_chart/README
git rm vendor/plugins/open_flash_chart/Rakefile
git rm vendor/plugins/open_flash_chart/assets/javascripts/swfobject.js
git rm vendor/plugins/open_flash_chart/assets/open-flash-chart-bar-clicking.swf
git rm vendor/plugins/open_flash_chart/assets/open-flash-chart.swf
git rm vendor/plugins/open_flash_chart/init.rb
git rm vendor/plugins/open_flash_chart/install.rb
git rm vendor/plugins/open_flash_chart/lib/open_flash_chart.rb
git rm vendor/plugins/open_flash_chart/lib/open_flash_chart/area_base.rb
git rm vendor/plugins/open_flash_chart/lib/open_flash_chart/area_hollow.rb
git rm vendor/plugins/open_flash_chart/lib/open_flash_chart/area_line.rb
git rm vendor/plugins/open_flash_chart/lib/open_flash_chart/arrow.rb
git rm vendor/plugins/open_flash_chart/lib/open_flash_chart/bar.rb
git rm vendor/plugins/open_flash_chart/lib/open_flash_chart/bar_3d.rb
git rm vendor/plugins/open_flash_chart/lib/open_flash_chart/bar_base.rb
git rm vendor/plugins/open_flash_chart/lib/open_flash_chart/bar_filled.rb
git rm vendor/plugins/open_flash_chart/lib/open_flash_chart/bar_glass.rb
git rm vendor/plugins/open_flash_chart/lib/open_flash_chart/bar_sketch.rb
git rm vendor/plugins/open_flash_chart/lib/open_flash_chart/bar_stack.rb
git rm vendor/plugins/open_flash_chart/lib/open_flash_chart/base.rb
git rm vendor/plugins/open_flash_chart/lib/open_flash_chart/candle.rb
git rm vendor/plugins/open_flash_chart/lib/open_flash_chart/chart.rb
git rm vendor/plugins/open_flash_chart/lib/open_flash_chart/dot_base.rb
git rm vendor/plugins/open_flash_chart/lib/open_flash_chart/h_bar.rb
git rm vendor/plugins/open_flash_chart/lib/open_flash_chart/legend.rb
git rm vendor/plugins/open_flash_chart/lib/open_flash_chart/line.rb
git rm vendor/plugins/open_flash_chart/lib/open_flash_chart/line_base.rb
git rm vendor/plugins/open_flash_chart/lib/open_flash_chart/line_dot.rb
git rm vendor/plugins/open_flash_chart/lib/open_flash_chart/line_hollow.rb
git rm vendor/plugins/open_flash_chart/lib/open_flash_chart/line_style.rb
git rm vendor/plugins/open_flash_chart/lib/open_flash_chart/linear_regression.rb
git rm vendor/plugins/open_flash_chart/lib/open_flash_chart/menu.rb
git rm vendor/plugins/open_flash_chart/lib/open_flash_chart/ofc_ajax.rb
git rm vendor/plugins/open_flash_chart/lib/open_flash_chart/open_flash_chart_object.rb
git rm vendor/plugins/open_flash_chart/lib/open_flash_chart/pie.rb
git rm vendor/plugins/open_flash_chart/lib/open_flash_chart/radar_axis.rb
git rm vendor/plugins/open_flash_chart/lib/open_flash_chart/radar_axis_labels.rb
git rm vendor/plugins/open_flash_chart/lib/open_flash_chart/radar_spoke_labels.rb
git rm vendor/plugins/open_flash_chart/lib/open_flash_chart/scatter.rb
git rm vendor/plugins/open_flash_chart/lib/open_flash_chart/scatter_line.rb
git rm vendor/plugins/open_flash_chart/lib/open_flash_chart/shape.rb
git rm vendor/plugins/open_flash_chart/lib/open_flash_chart/sugar.rb
git rm vendor/plugins/open_flash_chart/lib/open_flash_chart/tags.rb
git rm vendor/plugins/open_flash_chart/lib/open_flash_chart/title.rb
git rm vendor/plugins/open_flash_chart/lib/open_flash_chart/tooltip.rb
git rm vendor/plugins/open_flash_chart/lib/open_flash_chart/upload_image.rb
git rm vendor/plugins/open_flash_chart/lib/open_flash_chart/x_axis.rb
git rm vendor/plugins/open_flash_chart/lib/open_flash_chart/x_axis_label.rb
git rm vendor/plugins/open_flash_chart/lib/open_flash_chart/x_axis_labels.rb
git rm vendor/plugins/open_flash_chart/lib/open_flash_chart/x_legend.rb
git rm vendor/plugins/open_flash_chart/lib/open_flash_chart/y_axis.rb
git rm vendor/plugins/open_flash_chart/lib/open_flash_chart/y_axis_base.rb
git rm vendor/plugins/open_flash_chart/lib/open_flash_chart/y_axis_label.rb
git rm vendor/plugins/open_flash_chart/lib/open_flash_chart/y_axis_labels.rb
git rm vendor/plugins/open_flash_chart/lib/open_flash_chart/y_axis_right.rb
git rm vendor/plugins/open_flash_chart/lib/open_flash_chart/y_legend.rb
git rm vendor/plugins/open_flash_chart/lib/open_flash_chart/y_legend_right.rb
git rm vendor/plugins/open_flash_chart/tasks/open_flash_chart_tasks.rake
git rm vendor/plugins/open_flash_chart/test/open_flash_chart_test.rb

