test:
  rpx_key: 18c3db9c36e3ce844af615637cfc9ffbac08448f
  recap_pub_key: 6LcbaboSAAAAADbBxT9yLOJ7CoLWLsuAfZr-aL-H
  recap_priv_key: 6LcbaboSAAAAACJMtxxfExG5dm_GcDHuZl9WVjZG
  google_js_api: ABQIAAAAi_F8JNAI9__oCG-KzCfTYhTJQa0g3IQ9GZqIMmInSLzwtGDKaBQ6kTvHNGROiENaALqema6YZJEh2Q
production:
  http_user: 'fedisking'
  http_pwd: 'newcircusontheweb'
  rpx_key: 18c3db9c36e3ce844af615637cfc9ffbac08448f
  recap_pub_key: 6Ldze70SAAAAAEyhtck2OXmfPFePGJibBQjqSgUL
  recap_priv_key: 6Ldze70SAAAAAE2yzHIS8MyL5X_Ahii1b1DsRofU
  google_js_api: ABQIAAAAi_F8JNAI9__oCG-KzCfTYhRg8WVEAiyQiHsswWA4KFnYAQDpyhTStZo1E46IgoXdAwYarvDyOXb7FQ
  facebook_app_api_key: dabaa5ee23cd2acb8c46f1320313db78
  facebook_app_id: 152722804740985
  smtp_server_host: 'smtp.gmail.com'
  smtp_server_port: '587'
  smtp_server_domain: 'gmail.com'
  smtp_server_pwd: badnaam1
  site_admin_email: 'voteableteam@gmail.com'
  personal_email: 'asitkmishra@gmail.com'
  smtp_server_domain:
  site_name: "Voteable"
  admin_pwd: 'd0ntd01t'
  admin_uname: 'edministrator'
  admin_role_name: 'admin'
  user_role_name: 'user'
  stock_pwd: 't'
development:
  http_user: 'lefthan%ed'
  http_pwd: 'when_not_3roken'
  rpx_key: 18c3db9c36e3ce844af615637cfc9ffbac08448f
  recap_pub_key: 6LcbaboSAAAAADbBxT9yLOJ7CoLWLsuAfZr-aL-H
  recap_priv_key: 6LcbaboSAAAAACJMtxxfExG5dm_GcDHuZl9WVjZG
  google_js_api: ABQIAAAAi_F8JNAI9__oCG-KzCfTYhTJQa0g3IQ9GZqIMmInSLzwtGDKaBQ6kTvHNGROiENaALqema6YZJEh2Q
  yahoo_map: 3JVKXcvV34GeDldCLLrB01S1Lo.XukcaSbm9mbyZXmf9fn6VnhW6dAlX.Agk
  google_map: ABQIAAAAi_F8JNAI9__oCG-KzCfTYhTJQa0g3IQ9GZqIMmInSLzwtGDKaBQ6kTvHNGROiENaALqema6YZJEh2Q
  facebook_app_api_key: dabaa5ee23cd2acb8c46f1320313db78
  facebook_app_id: 152722804740985
  smtp_server_host: 'smtp.gmail.com'
  smtp_server_port: '587'
  smtp_server_domain: 'gmail.com'
  smtp_server_pwd: badnaam1
  site_admin_email: 'voteableteam@gmail.com'
  personal_email: 'asitkmishra@gmail.com'
  smtp_server_domain:
  site_name: "Voteable"
  admin_pwd: 't'
  admin_uname: 'admin'
  admin_role_name: 'admin'
  user_role_name: 'user'
  stock_pwd: 't'
staging:
  #good for http://server
  rpx_key: 18c3db9c36e3ce844af615637cfc9ffbac08448f
#good for http://server
  recap_pub_key: 6Lfy_LsSAAAAAGC0SsG1poLUSUjTv2X28wIzo3I4
  recap_priv_key: 6Lfy_LsSAAAAAM6D2GfohESk5qMkcIiP7CyZFy3L
   #good for http://server
  google_js_api: ABQIAAAAi_F8JNAI9__oCG-KzCfTYhQaOzcbF5ealenFI9Pv5eWXfr2UbRT6PT_rSQkEp3MO8jJPIzz7SFwwLw

  