development:
  api_key: dabaa5ee23cd2acb8c46f1320313db78
  secret_key: c599197636acfecea3fdc37b9f2dd95a
  canvas_page_name: votechek
  callback_url: http://web1.tunnlr.com:11299
  app_id: 152722804740985
  pretty_errors: true
  set_asset_host_to_callback_url: true
  tunnel:
    public_host_username: tunnlr1783
    public_host: ssh1.tunnlr.com
    public_port: 11299
    local_port: 80
