development:
  mem_limit: 20M
  enable_star: true
production:
  mem_limit: 20M
  enable_star: true
  searchd_file_path: /var/www/voteable/shared/db/sphinx/prod
  enable_star: true
  query_log_file: /var/www/voteable/shared/log/searchd.query.log
  config_file: /var/www/voteable/shared/config/prod_sphinx.conf
  searchd_log_file: /var/www/voteable/shared/log/searchd.log
  morphology: stem_en
  pid_file: /var/www/voteable/shared/pids/searchd_production.pid
  bin_path: '/usr/local/bin/'

  #########following is gold configuration
#  mem_limit: 20M
#  enable_star: true
#  searchd_file_path: /var/www/votechek/shared/sphinx
#  enable_star: true
#  query_log_file: /var/www/votechek/shared/log/searchd.query.log
#  config_file: /var/www/votechek/shared/config/sphinx.conf
#  mem_limit: 20M
#  searchd_log_file: /var/www/votechek/shared/log/searchd.log
#  morphology: stem_en
#  pid_file: /var/www/votechek/shared/log/searchd.production.pid

  